### ISSUE TITLE
Uninstallable mofapy2 version

### ISSUE THREAD

**Issue by yeswzc** [willtownes/nsf-paper#11]
Hi, I wantted to install the version of mofapy2 you used, but it seems not installable (see below). Can I install a different version?

`pip install git+git://github.com/bioFAM/mofapy2.git@8f6ffcb5b18d22b3f44ff2a06bcb92f2806afed0`

> Collecting git+git://github.com/bioFAM/mofapy2.git@8f6ffcb5b18d22b3f44ff2a06bcb92f2806afed0
>   Cloning git://github.com/bioFAM/mofapy2.git (to revision 8f6ffcb5b18d22b3f44ff2a06bcb92f2806afed0) to /tmp/pip-req-build-llimfara
>   Running command git clone --filter=blob:none --quiet git://github.com/bioFAM/mofapy2.git /tmp/pip-req-build-llimfara
>   fatal: unable to look up github.com (port 9418) (Name or service not known)
>   error: subprocess-exited-with-error
> 
>   × git clone --filter=blob:none --quiet git://github.com/bioFAM/mofapy2.git /tmp/pip-req-build-llimfara did not run successfully.
>   │ exit code: 128
>   ╰─> See above for output.
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: subprocess-exited-with-error
> 
> × git clone --filter=blob:none --quiet git://github.com/bioFAM/mofapy2.git /tmp/pip-req-build-llimfara did not run successfully.
> │ exit code: 128
> ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by willtownes** [comment]
Sure, you can try a different version. I specified that commit in the paper because their package was under active development and it was the version I downloaded at that point in time. If you have trouble installing it I would recommend contacting the MEFISTO team directly.

**Comment by yeswzc** [comment]
I see. Thank you!
