### ISSUE TITLE
Some question

### ISSUE THREAD

**Issue by zyb0619** [willtownes/nsf-paper#3]
Dear @willtownes ,

Thanks for your code! I meet some troubles when I run https://github.com/willtownes/nsf-paper/blob/main/simulations/bm_mixed/01_data_generation.ipy. I find there are some conflict among my dependencies. 
![1](https://user-images.githubusercontent.com/103835570/225902190-9e6e2bb8-ca0d-464e-85f7-3c0ed2bb86be.png)
But I already installed werkzeug.
Could you please tell me the version of janitor used in your virtual environment.

Best,
zyb

**Comment by willtownes** [comment]
Thanks for the question. I unfortunately can't remember the exact version I used, but it would probably be somewhere close to [v20.14](https://github.com/pyjanitor-devs/pyjanitor/releases/tag/v0.20.14). The virtual environment I had everything on got wiped out a while ago and I foolishly failed to save the list of dependencies. Sorry about that! I don't think werkzeug should be needed as I haven't seen that package before. Hope that helps.
